### PR TITLE
Minimize/insertions

### PR DESCRIPTION
**Pull request by DovahCraft**

### CODE REVIEW

**Comment by DovahCraft** [comment]
@tdhock Can you look over my .travis.yml file to see why the No such file or directory error is prompting and stopping the build with gtest?

**Comment by tdhock** [comment]
in your build log I see
```
$ cd /usr/src/gtest
$ sudo cmake CMakeLists.txt
$ sudo make
$ sudo cp *.a /usr/lib
$ sudo mkdir /usr/local/lib/gtest
$ sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
$ sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
$ g++ -std=c++14 -g -o partialSelect PartialModelSelectionMain.cpp PartialModelSelection.cpp -pthread -lgtest && ./partialSelect
g++: error: PartialModelSelectionMain.cpp: No such file or directory
g++: error: PartialModelSelection.cpp: No such file or directory
The command "g++ -std=c++14 -g -o partialSelect PartialModelSelectionMain.cpp PartialModelSelection.cpp -pthread -lgtest && ./partialSelect" exited with 1.
```
at the top you change to /usr/src/gtest so I guess you are still in that directory when you run g++ and the cpp files are not found in that directory. fix by changing back to your repo where those cpp files are before compiling with g++

also why are you doing all these operations in /usr/src/gtest? is that for installing gtest? isn't there an easier way? on my system I can do `apt install libgtest-dev` ... did you try a web search to see how other people setup C++ projects with google test?

it should not be this complicated!

**Comment by DovahCraft** [comment]
I got these instructions from the github repo you sent me before, which is here: https://github.com/deftio/travis-ci-cpp-example

They have gtest installation instructions that I tried to follow and put into this .yml file. 

Can you tell me how to refactor this to just use apt install libgtest-dev instead? This seems very complicated indeed.

Also, did you see my emails? I have been sending questions there too.

Thanks

**Comment by tdhock** [comment]
typically you should not merge with master unless all tests are passing

**Comment by tdhock** [comment]
this issue https://github.com/roboticslab-uc3m/questions-and-answers/issues/41 seems to indicate that installing gtest is more complicated than a simple "apt install" command. possible solutions
1. whatever you did to install gtest on your computer, do the same thing on travis.
2. let's stop using gtest and instead just write tests in an R package. anyway we should eventually write an R package interface for the C++ code so maybe now is a good time to start doing that.

**Pull request merged**
